steps:
  install_and_test:
    name: Install & Test
    image: node:20
    commands:
      - set -eu
      - |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi
      - npm run test -- --coverage --coverageReporters=lcov --passWithNoTests
    when:
      branch: [main]
      event: [push, manual]

  upload_coverage_codecov:
    name: Upload Coverage to Codecov
    image: alpine:latest
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - set -eu
      - apk add --no-cache curl bash
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov --token "$CODECOV_TOKEN" --fail-under=60 --file=coverage/lcov.info
    depends_on: [install_and_test]
    when:
      branch: [main]
      event: [push, manual]

  docker_build_push:
    name: Docker Build & Push (Docker Hub)
    image: docker:24.0.7-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_TOKEN:
        from_secret: DOCKER_TOKEN
    commands:
      - set -eu
      - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
      - IMAGE_REPO="wellrcosta/${CI_REPO_NAME}"
      - SHA="${CI_COMMIT_SHA}"
      - docker build -t "${IMAGE_REPO}:latest" -t "${IMAGE_REPO}:${SHA}" .
      - docker push "${IMAGE_REPO}:latest"
      - docker push "${IMAGE_REPO}:${SHA}"
      - echo "${SHA}" > .tag_sha
      - docker rmi "${IMAGE_REPO}:latest" || true
      - docker rmi "${IMAGE_REPO}:${SHA}" || true
    depends_on: [upload_coverage_codecov]
    when:
      branch: [main]
      event: [push, manual]

  bump_tag_commit:
    name: Bump tag in deploy.values.yaml
    image: alpine:3.20
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - set -eu
      - apk add --no-cache git yq
      # 0) valida secret (aborta se vazio)
      - |
        if [ -z "${GITHUB_TOKEN:-}" ]; then
          echo "GITHUB_TOKEN ausente (defina o PAT com escopo 'repo' no Woodpecker: Secrets do repo ou globais)" >&2
          exit 1
        fi
      # 1) identidade git e safe dir
      - git config --global user.email "ci@wellrcosta.dev"
      - git config --global user.name  "woodpecker-bot"
      - git config --global --add safe.directory /woodpecker/src || true
      # 2) owner/repo 100% confiável pelas envs nativas
      - REPO_FULL="${CI_REPO_OWNER}/${CI_REPO_NAME}"
      # 3) SHA a gravar
      - |
        if [ -f .tag_sha ]; then
          SHA="$(cat .tag_sha)"
        else
          SHA="${CI_COMMIT_SHA}"
        fi
        echo "Atualizando tag para ${SHA}"
      # 4) atualiza deploy.values.yaml
      - |
        if [ ! -f deploy.values.yaml ]; then
          echo "deploy.values.yaml não encontrado na raiz." >&2
          exit 1
        fi
        yq -i '.tag = strenv(SHA)' deploy.values.yaml
        git add deploy.values.yaml
        git commit -m "chore(ci): update image tag to ${SHA}" || true
      # 5) push usando x-access-token (não vaza o token)
      - git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO_FULL}.git"
      - git push origin HEAD:main
    depends_on: [docker_build_push]
    when:
      branch: [main]
      event: [push, manual]

  apply_secrets:
    name: Apply Secrets to K8s
    image: bitnami/kubectl:1.30
    environment:
      DOCKER_SERVER: https://index.docker.io/v1/
      KUBE_NAMESPACE: ${KUBE_NAMESPACE=local-services}
      APP_NAME: ${APP_NAME=${CI_REPO_NAME}}
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_TOKEN:
        from_secret: DOCKER_TOKEN
    commands:
      - set -eu
      - mkdir -p $HOME/.kube && echo "$KUBE_CONFIG" > $HOME/.kube/config && chmod 600 $HOME/.kube/config
      - kubectl -n "${KUBE_NAMESPACE}" create secret docker-registry registry-cred \
        --docker-server="${DOCKER_SERVER}" \
        --docker-username="${DOCKER_USER}" \
        --docker-password="${DOCKER_TOKEN}" \
        --dry-run=client -o yaml | kubectl apply -f -
      - |
        NAME="${APP_NAME}"
        NS="${KUBE_NAMESPACE}"
        TMP=/tmp/secret.yaml
        {
          echo "apiVersion: v1"
          echo "kind: Secret"
          echo "metadata:"
          echo "  name: ${NAME}-secrets"
          echo "  namespace: ${NS}"
          echo "type: Opaque"
          echo "stringData:"
          echo "  dotenv: |"
          env | awk -F= '/^ENV__/ {
            key=substr($1,6); val=$0; sub(/^[^=]*=/,"",val);
            printf "    %s=%s\n", key, val
          }'
          env | awk -F= '/^ENV__/ {
            key=substr($1,6); val=$0; sub(/^[^=]*=/,"",val);
            gsub(/\\/,"\\\\",val); gsub(/"/,"\\\"",val);
            printf "  \"%s\": \"%s\"\n", key, val
          }'
        } > "$TMP"
        kubectl apply -f "$TMP"
    depends_on: [bump_tag_commit]
    when:
      branch: [main]
      event: [push, manual]
