# .woodpecker.yml — Docker Hub + tag por SHA + bump automático

steps:
  install_and_test:
    name: Install & Test
    image: node:20
    commands:
      - npm ci
      - npm run test -- --coverage
    when:
      branch: [main]
      event: [push, manual]

  upload_coverage_codecov:
    name: Upload Coverage to Codecov
    image: alpine:latest
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - apk add --no-cache curl bash
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov --token "$CODECOV_TOKEN" --fail-under=60 --file=coverage/lcov.info
    when:
      branch: [main]
      event: [push, manual]

  docker_build_push:
    name: Docker Build & Push (Docker Hub)
    image: docker:24.0.7-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER # seu usuário do Docker Hub
      DOCKER_TOKEN:
        from_secret: DOCKER_TOKEN # access token do Docker Hub
    commands:
      - set -eu
      - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USER" --password-stdin
      - SHA="${CI_COMMIT_SHA}"
      - docker build -t "${DOCKER_USER}/${CI_REPO_NAME}:latest" -t "${DOCKER_USER}/${CI_REPO_NAME}:${SHA}" .
      - docker push "${DOCKER_USER}/${CI_REPO_NAME}:latest"
      - docker push "${DOCKER_USER}/${CI_REPO_NAME}:${SHA}"
      - echo "${SHA}" > .tag_sha
      - docker rmi "${DOCKER_USER}/${CI_REPO_NAME}:latest" || true
      - docker rmi "${DOCKER_USER}/${CI_REPO_NAME}:${SHA}" || true
    when:
      branch: [main]
      event: [push, manual]

  bump_tag_commit:
    name: Bump tag in deploy.values.yaml
    image: alpine:3.20
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN # PAT com escopo "repo"
    commands:
      - apk add --no-cache git yq
      - git config --global user.email "ci@wellrcosta.dev"
      - git config --global user.name  "woodpecker-bot"
      - git remote set-url origin "https://wellrcosta:${GITHUB_TOKEN}@github.com/wellrcosta/${CI_REPO_NAME}.git"
      - SHA=$(cat .tag_sha)
      - |
        if [ -f deploy.values.yaml ]; then
          yq -i ".tag = \"${SHA}\"" deploy.values.yaml
          git add deploy.values.yaml
          git commit -m "chore(ci): update image tag to ${SHA}" || true
          git push origin HEAD:main
        else
          echo "deploy.values.yaml não encontrado na raiz."
          exit 1
        fi
    when:
      branch: [main]
      event: [push, manual]

  apply_secrets:
    name: Apply Secrets to K8s
    image: bitnami/kubectl:1.30
    environment:
      # servidor correto do Docker Hub para imagePullSecret
      DOCKER_SERVER: https://index.docker.io/v1/
      KUBE_NAMESPACE: ${KUBE_NAMESPACE=local-services}
      APP_NAME: ${APP_NAME=${CI_REPO_NAME}}
      KUBE_CONFIG:
        from_secret: KUBE_CONFIG
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_TOKEN:
        from_secret: DOCKER_TOKEN
    commands:
      - mkdir -p $HOME/.kube && echo "$KUBE_CONFIG" > $HOME/.kube/config && chmod 600 $HOME/.kube/config
      # imagePullSecret (necessário se o repo de imagens for privado; público também funciona, não atrapalha)
      - kubectl -n ${KUBE_NAMESPACE} create secret docker-registry registry-cred \
        --docker-server="${DOCKER_SERVER}" \
        --docker-username="${DOCKER_USER}" \
        --docker-password="${DOCKER_TOKEN}" \
        --dry-run=client -o yaml | kubectl apply -f -
      # Secret do app a partir de ENV__* (ENV__FOO__BAR -> "FOO.BAR": "valor" e espelho .env)
      - |
        NAME=${APP_NAME}
        NS=${KUBE_NAMESPACE}
        TMP=/tmp/secret.yaml
        {
          echo "apiVersion: v1"
          echo "kind: Secret"
          echo "metadata:"
          echo "  name: ${NAME}-secrets"
          echo "  namespace: ${NS}"
          echo "type: Opaque"
          echo "stringData:"
          echo "  dotenv: |"
          env | awk -F= '/^ENV__/ {
            key=substr($1,6); val=$0; sub(/^[^=]*=/,"",val);
            printf "    %s=%s\n", key, val
          }'
          env | awk -F= '/^ENV__/ {
            key=substr($1,6); val=$0; sub(/^[^=]*=/,"",val);
            gsub(/\\/,"\\\\",val); gsub(/"/,"\\\"",val);
            printf "  \"%s\": \"%s\"\n", key, val
          }'
        } > $TMP
        kubectl apply -f $TMP
    when:
      branch: [main]
      event: [push, manual]
