name: pedidos
namespace: local-services
imageRepo: docker.io/wellrcosta/pedidos
tag: 2197a0ab0c761711a93f15b4337aa7e8e5526941
port: 80
expose: http
host: pedidos.192.168.1.150.nip.io
ingressClassName: traefik
replicas: 2
readinessProbe:
  enabled: true
  path: /health
livenessProbe:
  enabled: true
  path: /health
