name: pedidos
namespace: local-services

imageRepo: ghcr.io/wellrcosta/pedidos
tag: latest
port: 80

expose: http
host: pedidos.192.168.1.150.nip.io
ingressClassName: traefik

replicas: 2

readinessProbe:
  enabled: true
  path: /health
livenessProbe:
  enabled: true
  path: /health
